title: kriscience
email: kris@amk.zone
description: >-
  I share my experience and a pragmatic approach to software development.  Also
  keep this a set of notes for myself.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krsc.amk.land"
github_username:  kkonopko

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
